### ISSUE TITLE
unable to parse invalid number

### ISSUE THREAD

**Issue by sirkubax** [novaquark/sysinfo_influxdb#30]
Hi
I did face following error:

    unable to parse 'network,fqdn=stg-host102,iface=eth0           recv_bytes=52i,recv_compressed=0i,recv_drop=0i,recv_errs=0i,recv_fifo=0i,recv_frame=0i,recv_multicast=0i,recv_packets=1i,trans_bytes=0i,trans_c|
arrier=0i,trans_colls=0i,trans_compressed=0i,trans_drop=0i,trans_errs=0i,trans_fifo=0i,trans_packets=0i': invalid number

It is on ubuntu 14.04
I did try verisons 0.9.2 and 0.9.2.1
http://s3.amazonaws.com/influxdb/influxdb_{{ versions.influxdb }}_amd64.deb

Should work with 0.9.2.1 based on:
https://github.com/influxdb/influxdb/issues/3606

What version does current master sysinfo_influxdb supports?
Any ideas?

**Comment by sirkubax** [comment]
Quick test with 0.9.3 is positive, though I do not like it fully, since 0.9.3 deb package is missing init start/stop script - so would create inconsistent config

**Comment by nemunaire** [comment]
Hi!

This issue is indeed releated to the https://github.com/influxdb/influxdb/issues/3519 breaking change, introduce in the 0.9.3.

When you did a `go get`, Go will fetch the latest revision of the client, so you get a `sysinfo_influxdb` ready for the 0.9.3. If you want to have a working `sysinfo_influxdb` with InfluxDB 0.9.2 and older, go to `$GOPATH/src/github.com/influxdb/influxdb` and perform a `git checkout 0.9.2`. Futher `go build` of `sysinfo_influxdb` will be compatible with the 0.9.2 revision.

**Comment by sirkubax** [comment]
I did switch to 0.9.3 finally. Thanks for the info :)

**Comment by ravimylavarapu** [comment]
check to see if any value that you are inserting is null, you could have the same issue if you are inserting a null value
